//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligenceCloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleFeature
    {
        public int FeatureId { get; set; }
        public int RoleId { get; set; }
        public Nullable<bool> FileUpload { get; set; }
        public Nullable<bool> FileDownload { get; set; }
        public Nullable<bool> ManageAccount { get; set; }
        public Nullable<bool> ManageRole { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
