//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligenceCloud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntelligenceCloudEntities : DbContext
    {
        public IntelligenceCloudEntities()
            : base("name=IntelligenceCloudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttachmentRecord> AttachmentRecord { get; set; }
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<CommunRecord> CommunRecord { get; set; }
        public virtual DbSet<ForensicSMS> ForensicSMS { get; set; }
        public virtual DbSet<ForensicContact> ForensicContact { get; set; }
        public virtual DbSet<Feature> Feature { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleFeature> RoleFeature { get; set; }
        public virtual DbSet<RoleMember> RoleMember { get; set; }
    }
}
